### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by belzebub40k** [freifunk-mwu/sites-ffmwu#1]
**Mandatory**
- [x] Create wrapper script to automate the build process of experimental builds
- [x] Experimental builds can't be signed when date changes
- [x] Check if release directory is empty before deploying

**Nice to have**
- [x] Add feature to clean current working dir
- [x] Improve logging
- [x] Add function to set symlinks after deploying
- [ ] Add function to promote testing to stable (and renew manifest)
- [x] Add script to automate signing of manifests from remote
- [x] Define individual output dirs per community/release
- [ ] Add commandline option to specify what to deploy (factory/sysupgrade/modules)
